### ISSUE TITLE
Can't find component; Commandbox 5.0

### ISSUE THREAD

**Issue by bshea5** [neokoenig/cfwheels-cli#33]
After upgrading to Commandbox 5.0, I get the following error on Windows 10:

![image](https://user-images.githubusercontent.com/3984775/76532650-27fa1800-6434-11ea-9f7c-4600bfba2960.png)

However, I still have access to the wheels cli commands, but I'm not sure what the above error affects as its not a tool I use too often. I've tried clearing out my .commandbox folder, and letting it instantiate a new one, then re-installing my modules, but still get the above.

**Comment by neokoenig** [comment]
Thanks, haven't had the opportunity to test v5 yet! Looks like it's just the path is wrong, and that's easily fixable (surprised it works under 4.x if I'm being honest!). Its only the command to list plugins from forgebox.

Will sort asap. T

**Comment by neokoenig** [comment]
Should be fixed now

**Comment by bshea5** [comment]
Seems like I still get the error after upgrading.

![image](https://user-images.githubusercontent.com/3984775/76717499-d5994f80-66f0-11ea-9aeb-2dcb4e246893.png)

**Comment by neokoenig** [comment]
Hmm, that's really weird, as that line doesn't exist in 0.3.5 - I wonder if it's a caching issue? Can you try `artifacts list`  - it should appear in there, and then `artifacts remove cfwheels-cli` and then `install cfwheels-cli` ? Hopefully that should definitely get the latest version.

**Comment by bshea5** [comment]
Fix works on my macOS. Will try again on Windows when I can and will try your suggestion.

**Comment by bshea5** [comment]
I removed it from the artifacts list, uninstalled and reinstalled, but still see the warning on my Windows machine. Seems like the cli itself works though.

**Comment by neokoenig** [comment]
I think I buggered up the release somehow. I'll do a new one tomorrow - should sort it!

**Comment by bshea5** [comment]
Let me know when you do and I'll give it a go. I'll be at home on my Windows machine more with the outbreak going on.

**Comment by neokoenig** [comment]
ok, pushed out 0.3.6
